title: "My Blog"
author: "BNS Kumar"
description: "Exploring AI, Large Language Models, and Machine Learning."
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

show_excerpts: true  # Shows post previews instead of full posts
paginate: 5
paginate_path: "/page:num/"
search: true
minimal_mistakes_skin: "default"  # Other options: "dark", "air", "contrast"

# ✅ ADD THIS TO ENABLE NAVIGATION
include: ["_pages"]
header_pages:
  - _pages/about.md
  - _pages/blog.md
  - _pages/contact.md

# Default layout for the homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"