title: "My Blog"
author: "BNS Kumar"
description: "Exploring AI, Large Language Models, and Machine Learning."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true  # Shows post previews instead of full posts
paginate: 5
paginate_path: "/page:num/"
